version: "3.8"

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    networks: [licnet]

  app:
    build: ./app
    restart: unless-stopped
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=${PORT}
      - BASE_URL=${BASE_URL}
      - ICS_TOKEN=${ICS_TOKEN}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_SECURE=${SMTP_SECURE}
      - FROM_EMAIL=${FROM_EMAIL}
      - ALERT_TO=${ALERT_TO}
      - TZ=Europe/Zurich
    depends_on:
      - redis
    ports:
      - "8080:8080"
    networks: [licnet]

networks:
  licnet: